name: Deploy

on:
  push:
    tags: [ "*" ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  maven-central:
    name: Maven Central
    runs-on: macos-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Cache Kotlin/Native toolchains
        uses: actions/cache@v4.3.0
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_PORTAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToMavenCentral -PVERSION_NAME=${GITHUB_REF_NAME#v}
